//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAPICodePack.Shell.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAPICodePack.Shell.Resources.LocalizedMessages", typeof(LocalizedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddToMostRecentlyUsedList cannot be changed while dialog is showing..
        /// </summary>
        internal static string AddToMostRecentlyUsedListCannotBeChanged {
            get {
                return ResourceManager.GetString("AddToMostRecentlyUsedListCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlwaysAppendDefaultExtension cannot be changed while dialog is showing..
        /// </summary>
        internal static string AlwaysAppendDefaultExtensionCannotBeChanged {
            get {
                return ResourceManager.GetString("AlwaysAppendDefaultExtensionCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was outside the bounds of the CommonFileDialogComboBox..
        /// </summary>
        internal static string ComboBoxIndexOutsideBounds {
            get {
                return ResourceManager.GetString("ComboBoxIndexOutsideBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name not available - dialog was canceled..
        /// </summary>
        internal static string CommonFileDialogCanceled {
            get {
                return ResourceManager.GetString("CommonFileDialogCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell item could not be created..
        /// </summary>
        internal static string CommonFileDialogCannotCreateShellItem {
            get {
                return ResourceManager.GetString("CommonFileDialogCannotCreateShellItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle provided cannot be IntPtr.Zero..
        /// </summary>
        internal static string CommonFileDialogInvalidHandle {
            get {
                return ResourceManager.GetString("CommonFileDialogInvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple files selected - the FileNames property should be used instead..
        /// </summary>
        internal static string CommonFileDialogMultipleFiles {
            get {
                return ResourceManager.GetString("CommonFileDialogMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple files selected - the Items property should be used instead..
        /// </summary>
        internal static string CommonFileDialogMultipleItems {
            get {
                return ResourceManager.GetString("CommonFileDialogMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name not available - dialog has not closed yet..
        /// </summary>
        internal static string CommonFileDialogNotClosed {
            get {
                return ResourceManager.GetString("CommonFileDialogNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common File Dialog requires Windows Vista or later..
        /// </summary>
        internal static string CommonFileDialogRequiresVista {
            get {
                return ResourceManager.GetString("CommonFileDialogRequiresVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Files.
        /// </summary>
        internal static string CommonFiltersOffice {
            get {
                return ResourceManager.GetString("CommonFiltersOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Picture Files.
        /// </summary>
        internal static string CommonFiltersPicture {
            get {
                return ResourceManager.GetString("CommonFiltersPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files.
        /// </summary>
        internal static string CommonFiltersText {
            get {
                return ResourceManager.GetString("CommonFiltersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not list processes locking resource..
        /// </summary>
        internal static string CouldNotListProcessesLockingResource {
            get {
                return ResourceManager.GetString("CouldNotListProcessesLockingResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register resource..
        /// </summary>
        internal static string CouldNotRegisterResource {
            get {
                return ResourceManager.GetString("CouldNotRegisterResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatePrompt cannot be changed while dialog is showing..
        /// </summary>
        internal static string CreatePromptCannotBeChanged {
            get {
                return ResourceManager.GetString("CreatePromptCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom controls cannot be removed from a File dialog once added..
        /// </summary>
        internal static string DialogControlCollectionCannotRemoveControls {
            get {
                return ResourceManager.GetString("DialogControlCollectionCannotRemoveControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control name cannot be null or zero length..
        /// </summary>
        internal static string DialogControlCollectionEmptyName {
            get {
                return ResourceManager.GetString("DialogControlCollectionEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonFileDialogMenuItem controls can only be added to CommonFileDialogMenu controls..
        /// </summary>
        internal static string DialogControlCollectionMenuItemControlsCannotBeAdded {
            get {
                return ResourceManager.GetString("DialogControlCollectionMenuItemControlsCannotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying controls collection while dialog is showing is not supported..
        /// </summary>
        internal static string DialogControlCollectionModifyingControls {
            get {
                return ResourceManager.GetString("DialogControlCollectionModifyingControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog cannot have more than one control with the same name..
        /// </summary>
        internal static string DialogControlCollectionMoreThanOneControl {
            get {
                return ResourceManager.GetString("DialogControlCollectionMoreThanOneControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog control must be removed from current collections first..
        /// </summary>
        internal static string DialogControlCollectionRemoveControlFirst {
            get {
                return ResourceManager.GetString("DialogControlCollectionRemoveControlFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnsureFileExists cannot be changed while dialog is showing..
        /// </summary>
        internal static string EnsureFileExistsCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsureFileExistsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnsurePathExists cannot be changed while dialog is showing..
        /// </summary>
        internal static string EnsurePathExistsCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsurePathExistsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnsureReadOnly cannot be changed while dialog is showing..
        /// </summary>
        internal static string EnsureReadonlyCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsureReadonlyCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnsureValidNames cannot be changed while dialog is showing..
        /// </summary>
        internal static string EnsureValidNamesCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsureValidNamesCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing to object failed..
        /// </summary>
        internal static string ExplorerBrowserBrowseToObjectFailed {
            get {
                return ResourceManager.GetString("ExplorerBrowserBrowseToObjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExplorerBrowser failed to get current view..
        /// </summary>
        internal static string ExplorerBrowserFailedToGetView {
            get {
                return ResourceManager.GetString("ExplorerBrowserFailedToGetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get icon size..
        /// </summary>
        internal static string ExplorerBrowserIconSize {
            get {
                return ResourceManager.GetString("ExplorerBrowserIconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error retrieving item count..
        /// </summary>
        internal static string ExplorerBrowserItemCount {
            get {
                return ResourceManager.GetString("ExplorerBrowserItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error retrieving selected item count..
        /// </summary>
        internal static string ExplorerBrowserSelectedItemCount {
            get {
                return ResourceManager.GetString("ExplorerBrowserSelectedItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error retrieving selection..
        /// </summary>
        internal static string ExplorerBrowserUnexpectedError {
            get {
                return ResourceManager.GetString("ExplorerBrowserUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error retrieving view items..
        /// </summary>
        internal static string ExplorerBrowserViewItems {
            get {
                return ResourceManager.GetString("ExplorerBrowserViewItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not list processes locking resource. Failed to get size of result..
        /// </summary>
        internal static string FailedToGetSizeOfResult {
            get {
                return ResourceManager.GetString("FailedToGetSizeOfResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsExpandedMode cannot be changed while dialog is showing..
        /// </summary>
        internal static string IsExpandedModeCannotBeChanged {
            get {
                return ResourceManager.GetString("IsExpandedModeCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom categories cannot be added while recent documents tracking is turned off..
        /// </summary>
        internal static string JumpListCustomCategoriesDisabled {
            get {
                return ResourceManager.GetString("JumpListCustomCategoriesDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file type is not registered with this application..
        /// </summary>
        internal static string JumpListFileTypeNotRegistered {
            get {
                return ResourceManager.GetString("JumpListFileTypeNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpListLink&apos;s path is required and cannot be null..
        /// </summary>
        internal static string JumpListLinkPathRequired {
            get {
                return ResourceManager.GetString("JumpListLinkPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpListLink&apos;s title is required and cannot be null..
        /// </summary>
        internal static string JumpListLinkTitleRequired {
            get {
                return ResourceManager.GetString("JumpListLinkTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative numbers are not allowed for the ordinal position..
        /// </summary>
        internal static string JumpListNegativeOrdinalPosition {
            get {
                return ResourceManager.GetString("JumpListNegativeOrdinalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of window has failed, view inner exception for details..
        /// </summary>
        internal static string MessageListenerCannotCreateWindow {
            get {
                return ResourceManager.GetString("MessageListenerCannotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window class could not be registered, check inner exception for more details..
        /// </summary>
        internal static string MessageListenerClassNotRegistered {
            get {
                return ResourceManager.GetString("MessageListenerClassNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message filter registration failed..
        /// </summary>
        internal static string MessageListenerFilterUnableToRegister {
            get {
                return ResourceManager.GetString("MessageListenerFilterUnableToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No listener handled of that value is registered..
        /// </summary>
        internal static string MessageListenerFilterUnknownListenerHandle {
            get {
                return ResourceManager.GetString("MessageListenerFilterUnknownListenerHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create window on the listener thread because there is no existing window on the listener thread..
        /// </summary>
        internal static string MessageListenerNoWindowHandle {
            get {
                return ResourceManager.GetString("MessageListenerNoWindowHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavigateToShortcut cannot be changed while dialog is showing..
        /// </summary>
        internal static string NavigateToShortcutCannotBeChanged {
            get {
                return ResourceManager.GetString("NavigateToShortcutCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent cannot be null..
        /// </summary>
        internal static string NavigationLogNullParent {
            get {
                return ResourceManager.GetString("NavigationLogNullParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method or operation is not implemented..
        /// </summary>
        internal static string NotImplementedException {
            get {
                return ResourceManager.GetString("NotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverwritePrompt cannot be changed while dialog is showing..
        /// </summary>
        internal static string OverwritePromptCannotBeChanged {
            get {
                return ResourceManager.GetString("OverwritePromptCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was outside the bounds of the CommonFileDialogRadioButtonList..
        /// </summary>
        internal static string RadioButtonListIndexOutOfBounds {
            get {
                return ResourceManager.GetString("RadioButtonListIndexOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestoreDirectory cannot be changed while dialog is showing..
        /// </summary>
        internal static string RestoreDirectoryCannotBeChanged {
            get {
                return ResourceManager.GetString("RestoreDirectoryCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved a null shell item from dialog..
        /// </summary>
        internal static string SaveFileNullItem {
            get {
                return ResourceManager.GetString("SaveFileNullItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultSaveFolder path not found..
        /// </summary>
        internal static string ShellLibraryDefaultSaveFolderNotFound {
            get {
                return ResourceManager.GetString("ShellLibraryDefaultSaveFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination array too small, or invalid arrayIndex..
        /// </summary>
        internal static string ShellObjectCollectionArrayTooSmall {
            get {
                return ResourceManager.GetString("ShellObjectCollectionArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have at least one shell object in the collection..
        /// </summary>
        internal static string ShellObjectCollectionEmptyCollection {
            get {
                return ResourceManager.GetString("ShellObjectCollectionEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert items into a read only list..
        /// </summary>
        internal static string ShellObjectCollectionInsertReadOnly {
            get {
                return ResourceManager.GetString("ShellObjectCollectionInsertReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove items from a read only list..
        /// </summary>
        internal static string ShellObjectCollectionRemoveReadOnly {
            get {
                return ResourceManager.GetString("ShellObjectCollectionRemoveReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration for change notification has failed..
        /// </summary>
        internal static string ShellObjectWatcherRegisterFailed {
            get {
                return ResourceManager.GetString("ShellObjectWatcherRegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change watched events while listening..
        /// </summary>
        internal static string ShellObjectWatcherUnableToChangeEvents {
            get {
                return ResourceManager.GetString("ShellObjectWatcherUnableToChangeEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowHiddenItems cannot be changed while dialog is showing..
        /// </summary>
        internal static string ShowHiddenItemsCannotBeChanged {
            get {
                return ResourceManager.GetString("ShowHiddenItemsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show places list cannot be changed while dialog is showing..
        /// </summary>
        internal static string ShowPlacesListCannotBeChanged {
            get {
                return ResourceManager.GetString("ShowPlacesListCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Stock Icon identifier given is invalid ({0})..
        /// </summary>
        internal static string StockIconInvalidGuid {
            get {
                return ResourceManager.GetString("StockIconInvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child control&apos;s window handle cannot be zero..
        /// </summary>
        internal static string TabbedThumbnailZeroChildHandle {
            get {
                return ResourceManager.GetString("TabbedThumbnailZeroChildHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent window handle cannot be zero..
        /// </summary>
        internal static string TabbedThumbnailZeroParentHandle {
            get {
                return ResourceManager.GetString("TabbedThumbnailZeroParentHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabbedThumbnailProxyWindow has not been set..
        /// </summary>
        internal static string TasbarWindowProxyWindowSet {
            get {
                return ResourceManager.GetString("TasbarWindowProxyWindowSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid active Window is needed to update the Taskbar..
        /// </summary>
        internal static string TaskbarManagerValidWindowRequired {
            get {
                return ResourceManager.GetString("TaskbarManagerValidWindowRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array of buttons must contain at least 1 item..
        /// </summary>
        internal static string TaskbarWindowEmptyButtonArray {
            get {
                return ResourceManager.GetString("TaskbarWindowEmptyButtonArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool bar buttons for this window are already added. Please refer to the Remarks section of the AddButtons method for more information on updating the properties or hiding existing buttons..
        /// </summary>
        internal static string TaskbarWindowManagerButtonsAlreadyAdded {
            get {
                return ResourceManager.GetString("TaskbarWindowManagerButtonsAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is already set. It cannot be set more than once..
        /// </summary>
        internal static string TaskbarWindowValueSet {
            get {
                return ResourceManager.GetString("TaskbarWindowValueSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given control has not been added to the taskbar..
        /// </summary>
        internal static string ThumbnailManagerControlNotAdded {
            get {
                return ResourceManager.GetString("ThumbnailManagerControlNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window handle is invalid..
        /// </summary>
        internal static string ThumbnailManagerInvalidHandle {
            get {
                return ResourceManager.GetString("ThumbnailManagerInvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This preview has already been added..
        /// </summary>
        internal static string ThumbnailManagerPreviewAdded {
            get {
                return ResourceManager.GetString("ThumbnailManagerPreviewAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given preview has not been added to the taskbar..
        /// </summary>
        internal static string ThumbnailManagerPreviewNotAdded {
            get {
                return ResourceManager.GetString("ThumbnailManagerPreviewNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of buttons allowed is 7..
        /// </summary>
        internal static string ThumbnailToolbarManagerMaxButtons {
            get {
                return ResourceManager.GetString("ThumbnailToolbarManagerMaxButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null or empty arrays are not allowed..
        /// </summary>
        internal static string ThumbnailToolbarManagerNullEmptyArray {
            get {
                return ResourceManager.GetString("ThumbnailToolbarManagerNullEmptyArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not begin restart session. Unable to determine file locker..
        /// </summary>
        internal static string UnableToDetermineFileLocker {
            get {
                return ResourceManager.GetString("UnableToDetermineFileLocker", resourceCulture);
            }
        }
    }
}
